PowerSave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from landing_page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('bill_upload/', include('bill_upload.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bill_upload/urls.py
# bill_upload/urls.py
from django.urls import path
from . import views

app_name = 'bill_upload'

urlpatterns = [
    path('upload/', views.upload_bill, name='upload_bill'),
    path('success/', views.success, name='success'), 
    path('manual_input/', views.manual_input_view, name='manual_input'),
]

bill_upload/models.py
from django.db import models
from django.db.models.fields import DateTimeField
from django.db.models.fields import DecimalField
from django.db.models.fields import EmailField
from django.db.models.fields.files import FileField


class BillParam(models.Model):
    energy_contracted = models.DecimalField(max_digits=8, decimal_places=2)
    price_per_kwh = models.DecimalField(max_digits=8, decimal_places=4)
    mail = models.EmailField(default='default@example.com')  # Agrega el campo 'mail' con un valor predeterminado

    def __str__(self):
        return f"Parámetros de Factura de {self.mail}"


class BillUpload(models.Model):
    upload_date = models.DateTimeField(auto_now_add=True)
    bill_file = models.FileField(upload_to="")  # Cambia "bill_uploads/" por la ruta deseada para guardar las facturas

    def __str__(self):
        return f"{self.upload_date}"

contact_form/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models

# Create your models here.

bill_upload/forms.py
from django import forms
from .models import BillUpload
from .models import BillParam

class BillUploadForm(forms.ModelForm):
    class Meta:
        model = BillUpload
        fields = ['bill_file']

class BillParamForm(forms.ModelForm):
    class Meta:
        model = BillParam
        fields = ['energy_contracted', 'price_per_kwh', 'mail']

contact_form/forms.py
from django import forms

class Formulario(forms.Modelform):
    class Meta:
        

bill_upload/views.py
# views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail, EmailMessage
from .forms import BillUploadForm, BillParamForm
import mimetypes
from email.mime.image import MIMEImage



def upload_bill(request):
    if request.method == 'POST':
        form_upload = BillUploadForm(request.POST, request.FILES)
        if 'upload_bill' in request.POST and form_upload.is_valid():
            form_upload.save()
            send_mail_to_alvarogil137(request.POST, request.FILES)  # Llama a la función para enviar el correo electrónico
            return redirect('bill_upload:success')
    else:
        form_upload = BillUploadForm()

    return render(request, 'bill_upload/upload_bill.html', {
        'form_upload': form_upload,
    })

def manual_input_view(request):
    if request.method == 'POST':
        form_enter_data = BillParamForm(request.POST)
        if form_enter_data.is_valid():
            form_enter_data.save()
            send_mail_to_alvarogil137(request.POST)  # Llama a la función para enviar el correo electrónico
            return redirect('bill_upload:success')
    else:
        form_enter_data = BillParamForm()

    return render(request, 'bill_upload/manual_input.html', {'form': form_enter_data})


# views.py

from django.core.mail import send_mail, EmailMessage
import mimetypes

def send_mail_to_alvarogil137(post_data, files=None):
    
    if files:
        email = EmailMessage(
            'Nueva factura introducida',
            'cuerpo',
            'alvagilsan@gmail.com',    # Remitente del correo (reemplaza con tu dirección de correo)
            ['alvarogil137@gmail.com'],   # Lista de destinatarios (puedes agregar más correos separados por comas)
        )

        for file in files.getlist('bill_file'):
            # Abre el archivo en modo binario y lee su contenido como bytes
            with file.open(mode='rb') as f:
                email.attach(file.name, f.read(), file.content_type)

        email.send()
    else:
        energy_contracted = post_data['energy_contracted']
        price_per_kwh = post_data['price_per_kwh']
        mail = post_data['mail']

        data_to_send = f"Detalles de la factura:\n" \
                   f"Contrato de energía: {energy_contracted}\n" \
                   f"Precio por kWh: {price_per_kwh}\n" \
                   f"Correo electrónico: {mail}\n" \
                   f"..."  # Personaliza según tus campos del formulario

        send_mail(
            'Nuevos datos de factura introducidos',
            data_to_send,
            'alvagilsan@gmail.com',    # Remitente del correo (reemplaza con tu dirección de correo)
            ['alvarogil137@gmail.com'],   # Lista de destinatarios (puedes agregar más correos separados por comas)
            fail_silently=False,
        )






def success(request):
    return render(request, 'bill_upload/success.html')

contact_form/views.py
from django.shortcuts import render

# Create your views here.

landing_page/views.py
from django.shortcuts import render
# Create your views here.
def home(request):
    return render(request, 'home.html')

bill_upload/templates/bill_upload/manual_input.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Introducir Datos de Factura Manualmente</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #007BFF;
            color: #FFF;
            text-align: center;
            padding: 20px 0;
        }
        main {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            margin-bottom: 30px;
        }
        form {
            margin-bottom: 40px;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="email"],
        input[type="number"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #CCC;
            border-radius: 5px;
        }
        .submit-btn {
            background-color: #007BFF;
            color: #FFF;
            border: none;
            padding: 12px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <header>
        <h1>Introducir Datos de Factura Manualmente</h1>
    </header>
    <main>
        <form method="post">
            {% csrf_token %}
            <label for="id_energy_contracted">Energía Contratada (kWh):</label>
            {{ form.energy_contracted }}
            <label for="id_price_per_kwh">Precio por kWh:</label>
            {{ form.price_per_kwh }}
            <label for="id_mail">Correo Electrónico:</label>
            {{ form.mail }}
            <button class="submit-btn" type="submit">Guardar Datos</button>
        </form>
    </main>
</body>
</html>

bill_upload/templates/bill_upload/success.html
<!-- templates/bill_upload/success.html -->
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Éxito</title>
    <link rel="stylesheet" href="{% static 'success.css' %}">
</head>
<body>
    <div class="container">
        <h1>¡Factura Subida Exitosamente!</h1>
        <p>Gracias por subir tu factura o introducir los datos manualmente.</p>
        <p>Nos pondremos en contacto contigo en breve.</p>
    </div>
</body>
</html>

bill_upload/templates/bill_upload/upload_bill.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subir factura o introducir Datos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #007BFF;
            color: #FFF;
            text-align: center;
            padding: 20px 0;
        }
        main {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            margin-bottom: 30px;
        }
        h2 {
            margin: 30px 0 20px;
            border-bottom: 2px solid #007BFF;
            padding-bottom: 10px;
        }
        form {
            margin-bottom: 40px;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="file"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #CCC;
            border-radius: 5px;
        }
        .manual-input {
            text-align: center;
        }
        .manual-input button {
            background-color: #007BFF;
            color: #FFF;
            border: none;
            padding: 12px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <header>
        <h1>Subir Factura o Introducir Datos</h1>
    </header>
    <main>
        <h2>Subir Factura</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_bill_file">Selecciona tu factura:</label>
            {{ form_upload.bill_file }}
            <button type="submit" name="upload_bill">Subir factura</button>
        </form>

        <div class="manual-input">
            <p>También puedes introducir los datos de tu factura de manera manual.</p>
            <button onclick="window.location.href='{% url 'bill_upload:manual_input' %}'">Introducir manualmente</button>
        </div>
    </main>
</body>
</html>

landing_page/templates/home.html
{% extends 'layout.html' %}

{% block title %}PowerSave - Ahorro Garantizado en tu Factura de Luz{% endblock %}

{% block content %}

{% load static %}
<section class="hero">
    <div class="hero-content">
        <h2>¡Ahorro Garantizado en tu Factura de Luz!</h2>
        <p>Nuestra comparativa personalizada te asegura siempre una oferta más barata
            que tu factura actual.</p>
        <div class="cta-btn">
            <a href="{% url 'bill_upload:upload_bill' %}" class="cta-link">¡Empieza a ahorrar!</a>
        </div>
    </div>
</section>

<section class="features">
    <div class="feature-item feature-item-fullwidth">
        <div class="feature-card"> <!-- Nuevo div para la card -->
            <img src="{% static 'graphs.jpg' %}" alt="Feature 1">
            <h3>Comparativa Personalizada</h3>
            <p>Nuestro equipo analizará tu factura de luz y te ofrecerá una comparativa personalizada con las mejores
                ofertas disponibles.</p>
        </div>
    </div>
    <div class="feature-item feature-item-fullwidth">
        <div class="feature-card"> <!-- Nuevo div para la card -->
            <img src="image1.jpg" alt="Feature 1">
            <h3>Gestión Gratuita</h3>
            <p>Nuestra gestión y comparativa de facturas es completamente gratuita. No te cobramos ningún cargo
                adicional por nuestros servicios.</p>
        </div>
    </div>
    <div class="feature-item feature-item-fullwidth">
        <div class="feature-card"> <!-- Nuevo div para la card -->
            <img src="image1.jpg" alt="Feature 1">
            <h3>Ahorro Garantizado</h3>
            <p>Te garantizamos que la oferta que elijas será siempre más económica que tu factura actual, asegurándote
                un ahorro real.</p>
        </div>
    </div>
</section>

<section class="testimonials">
    <div class="testimonial">
        <img src="testimonial1.jpg" alt="Testimonial 1">
        <p>"¡Increíble servicio! Ahora ahorro mucho más en mi factura de luz. ¡Gracias por todo!"</p>
        <p class="testimonial-author">- Juan Pérez</p>
    </div>
    <div class="testimonial">
        <img src="testimonial2.jpg" alt="Testimonial 2">
        <p>"No puedo creer lo fácil que fue empezar a ahorrar con PowerSave. ¡Altamente recomendado!"</p>
        <p class="testimonial-author">- María Gómez</p>
    </div>
    <!-- Agregar más testimonios aquí -->
</section>

<section class="cta-section">
    <div class="cta-content">
        <h2>Únete a cientos de clientes satisfechos</h2>
        <p>¡Empieza a ahorrar en tu factura de luz hoy mismo!</p>
        <a href="{% url 'bill_upload:upload_bill' %}" class="cta-btn-large">Regístrate Ahora</a>
    </div>
</section>

{%endblock%}

landing_page/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Energia</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>

<body>
    <header>
        <div class="navbar">
            <div class="logo">
                <img src="{% static 'logo.png' %}" alt="Logo">
            </div>
            <div class="cta-btn">
                <a href="{% url 'bill_upload:upload_bill' %}" class="cta-link">¡Empieza a ahorrar!</a>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}

    <footer>
        <p>Derechos Reservados &copy; 2023 Tu Empresa</p>
    </footer>

</body>

</html>

landing_page/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">RR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="#" target="_blank">contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>